<a href="https://colab.research.google.com/github/arjunakula/Teaching1_Pytorch_LinearRegression/blob/master/Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#https://towardsdatascience.com/pytorch-fundamentals-50af6121d4a3

In [0]:
import numpy as np
import torch

In [0]:
# create a pytorch tensor from array
arr = [[3,4], [8,5]]
pyt_tensor = torch.Tensor(arr)

In [4]:
pyt_tensor

tensor([[3., 4.],
        [8., 5.]])

In [5]:
arr

[[3, 4], [8, 5]]

In [0]:
# create a tensor
ones_tensor = torch.ones((2,2))

In [7]:
ones_tensor

tensor([[1., 1.],
        [1., 1.]])

In [8]:
torch.manual_seed(0)

In [0]:
rand_tensor = torch.rand((2,2))

In [10]:
rand_tensor

tensor([[0.4963, 0.7682],
        [0.0885, 0.1320]])

In [0]:
rand_tensor = torch.rand((2,2))

In [12]:
rand_tensor

tensor([[0.3074, 0.6341],
        [0.4901, 0.8964]])

In [0]:
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(0)

In [14]:
torch.cuda.is_available()

True

In [0]:
np_arr = np.ones((2,2))

In [16]:
np_arr

array([[1., 1.],
       [1., 1.]])

In [0]:
pyt_tensor = torch.from_numpy(np_arr)

In [18]:
pyt_tensor

tensor([[1., 1.],
        [1., 1.]], dtype=torch.float64)

In [0]:
#convert tensor into numpy array
np_arr_from_tensor = pyt_tensor.numpy()

In [21]:
np_arr_from_tensor

array([[1., 1.],
       [1., 1.]])

In [0]:
##Tensor Operations

In [0]:
import numpy as np
import torch

In [0]:
#Resizing Tensor

In [0]:
pyt_tensor = torch.ones((2,2))

In [49]:
print(pyt_tensor.size())

torch.Size([2, 2])


In [0]:
pyt_tensor = pyt_tensor.view(4,-1)

In [51]:
pyt_tensor

tensor([[1.],
        [1.],
        [1.],
        [1.]])

In [52]:
pyt_tensor.size()

torch.Size([4, 1])

In [0]:
#Mathematical Operations

In [0]:
a = torch.ones((2,2))

In [0]:
b = torch.ones((2,2))

In [57]:
a+b

tensor([[2., 2.],
        [2., 2.]])

In [58]:
torch.add(a,b)

tensor([[2., 2.],
        [2., 2.]])

In [59]:
a.add_(b)

tensor([[2., 2.],
        [2., 2.]])

In [60]:
a

tensor([[2., 2.],
        [2., 2.]])

In [61]:
b

tensor([[1., 1.],
        [1., 1.]])

In [0]:
#Mean and Standard Deviation


In [0]:
a = torch.Tensor([[1,2],[3,4]])

In [72]:
a

tensor([[1., 2.],
        [3., 4.]])

In [73]:
a.size()

torch.Size([2, 2])

In [0]:
mean = a.mean(dim=0)

In [79]:
mean

tensor([2., 3.])

In [0]:
std = a.std(dim = 0)

In [81]:
std

tensor([1.4142, 1.4142])

In [0]:
#Variables and Gradients


In [0]:
import numpy as np

In [0]:
import torch

In [0]:
from torch.autograd import Variable

In [0]:
a = Variable(torch.ones((2,2)), requires_grad=True)

In [0]:
#y=5(x+1)^2

In [0]:
x = Variable(torch.ones(1), requires_grad=True)

In [0]:
y = 5 * (x+1) ** 2

In [0]:
y.backward()

In [91]:
print(x.grad)

tensor([20.])


In [93]:
print(y.grad)

None
