<a href="https://colab.research.google.com/github/arjunakula/Teaching1_Pytorch_LinearRegression/blob/master/Teaching1_Pytorch_QuadraticEquation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#https://medium.com/inspired-ideas/learning-a-quadratic-equation-with-pytorch-intro-to-pytorch-fa7bcef380a4

In [0]:
import torch
from torch import Tensor
from torch.nn import Linear, MSELoss, functional as F
from torch.optim import SGD, Adam, RMSprop
from torch.autograd import Variable
import numpy as np


In [0]:
# data generator
def generate_data(dataset_size=1000):
 
  # y = 10*x^2 + 5
  inputs = []
  labels = []
  
  for idx in range(0, dataset_size):
    x = np.random.randint(400)/400
    y = 10*x**2 + 5
    
    inputs.append([x])
    labels.append([y])
    
  
  
  return inputs,labels

In [0]:
inputs,labels = generate_data()

In [0]:
# define  model
class Net(torch.nn.Module):
  def __init__(self):
    super(Net, self).__init__()
    self.fc1 = Linear(1,6)
    self.fc2 = Linear(6,6)
    self.fc3 = Linear(6,1)
    
  def forward(self, x):
    x = F.dropout(F.relu(self.fc1(x)), p=0.5)
    x = F.relu(self.fc2(x))
    x = self.fc3(x)
    return x
  

In [0]:
model = Net()

In [170]:
list(model.parameters())

[Parameter containing:
 tensor([[-0.0170],
         [ 0.3269],
         [-0.3787],
         [-0.2873],
         [ 0.4757],
         [ 0.4488]], requires_grad=True), Parameter containing:
 tensor([0.1931, 0.8574, 0.9356, 0.9373, 0.4068, 0.4871], requires_grad=True), Parameter containing:
 tensor([[ 0.0838, -0.3057, -0.1399,  0.1036,  0.3133, -0.1036],
         [ 0.2770,  0.0847, -0.1088,  0.3307, -0.1857,  0.2925],
         [ 0.3358, -0.2938,  0.1714, -0.0778, -0.0998,  0.0213],
         [ 0.3200, -0.3115, -0.2310, -0.1484,  0.3842,  0.2495],
         [-0.0474, -0.2624,  0.1797, -0.0937, -0.2191, -0.1437],
         [ 0.1048,  0.4006, -0.1709, -0.2130,  0.3465, -0.3981]],
        requires_grad=True), Parameter containing:
 tensor([ 0.3428, -0.3629, -0.1308, -0.0256, -0.3035,  0.3761],
        requires_grad=True), Parameter containing:
 tensor([[ 0.3273, -0.3563, -0.1939, -0.1857, -0.2762, -0.1339]],
        requires_grad=True), Parameter containing:
 tensor([-0.1696], requires_grad=True)

In [0]:
#define loss function
criterion = MSELoss()

In [0]:
#define the optimizer
optimizer = SGD(model.parameters(), lr=0.001)

In [173]:
#training

num_epochs = 100

data_size = 1000

for epoch in range(num_epochs):
  X, y = generate_data()
  
  epoch_loss = 0
  
  for ix in range(1000):
    y_pred = model(Variable(Tensor(X[ix])))
    
    loss = criterion(y_pred, Variable(Tensor(y[ix]), requires_grad=False))
    
    epoch_loss = loss.item()
    
    optimizer.zero_grad()
    
    loss.backward()
    
    optimizer.step()
  
  print("Epoch: {} Loss: {}".format(epoch, epoch_loss))
  
  


Epoch: 0 Loss: 0.9996204972267151
Epoch: 1 Loss: 8.726326942443848
Epoch: 2 Loss: 2.5659310817718506
Epoch: 3 Loss: 0.30575570464134216
Epoch: 4 Loss: 6.177152633666992
Epoch: 5 Loss: 2.291241407394409
Epoch: 6 Loss: 0.23770804703235626
Epoch: 7 Loss: 2.471971273422241
Epoch: 8 Loss: 0.269185870885849
Epoch: 9 Loss: 0.0695965513586998
Epoch: 10 Loss: 1.4374921321868896
Epoch: 11 Loss: 0.20015574991703033
Epoch: 12 Loss: 0.6882319450378418
Epoch: 13 Loss: 1.1409944295883179
Epoch: 14 Loss: 0.2992177903652191
Epoch: 15 Loss: 0.4118342995643616
Epoch: 16 Loss: 1.9234875440597534
Epoch: 17 Loss: 0.012193364091217518
Epoch: 18 Loss: 0.1235385313630104
Epoch: 19 Loss: 0.02167138084769249
Epoch: 20 Loss: 0.034844376146793365
Epoch: 21 Loss: 0.6894477605819702
Epoch: 22 Loss: 0.003935690503567457
Epoch: 23 Loss: 0.09633100032806396
Epoch: 24 Loss: 0.3252476453781128
Epoch: 25 Loss: 0.10978292673826218
Epoch: 26 Loss: 0.1513780951499939
Epoch: 27 Loss: 0.014001763425767422
Epoch: 28 Loss: 0.180

In [0]:
#testing
model.eval()
test_data = generate_data(1)


In [187]:
test_data

([[0.12]], [[5.144]])

In [0]:
prediction = model(Variable(Tensor(test_data[0][0])))

In [189]:
prediction

tensor([6.1361], grad_fn=<AddBackward0>)

In [190]:
print("Prediction: {}".format(prediction.data[0]))

Prediction: 6.136107444763184


In [191]:
print("Expected: {}".format(test_data[1][0]))

Expected: [5.144]
